### PR TITLE
Bugfix/v2 bugfixes

### PR DESCRIPTION
**Pull request by tdespres**
Hello,

I use your awesome package in an Angular project.
I've found two odata-v2 bugs and here are corrections.
If you have any remarks, please let me know.

Thanks

### CODE REVIEW

**Comment by Soontao** [comment]
Hi @tdespres 

One question is that **what's the type of server which you are using**, because the `search` is not a standard operation in OData V2 spec, so it will have some little bit difference between each server variants.

1. create a ODataVariant
2. switch the `search` key by `ODataVariant` 

Regards,
Theo

**Comment by tdespres** [comment]
Hi @Soontao,

I use a SAP Gateway system.
Indeed, the **search** parameter does not exist as standard v2 parameter, but with Gateway systems, you can use it as a **Custom query option** :
https://www.odata.org/documentation/odata-version-2-0/uri-conventions/

Here is an example to use it with SAPUI5 framework :
https://stackoverflow.com/questions/49429130/how-do-i-set-the-search-url-parameter-in-sapui5-odata-requests

BR

**Comment by Soontao** [comment]
Hi @tdespres 

I'll release a new version to fix the `FunctionImport`, and for the custom param, please try this

```ts
OData.newParam().custom("access_token", "token_value"); // => $format=json&access_token=token_value
OData.newParam().custom("search", "v1"); // => $format=json&search=v1
```

**Comment by Soontao** [comment]
Hi @tdespres 

new version `2.17.0` released, please try this 


```ts
const TestServiceURL = "https://services.odata.org/V2/Northwind/Northwind.svc/$metadata"
const client = OData.New({
  metadataUri: TestServiceURL,
  variant: "sap-gateway"
})

const result = await client.newRequest({ // ODataRequest object
  collection: "Customers", // collection name
  params: client.newParam().search("any word") // => $format=json&search=%any word%
})

```

Regards,
Theo

**Comment by tdespres** [comment]
@Soontao, it works with custom param. 
New variant is also a nice alternative.
Thanks a lot for everything.

Another remark in **utils.ts** : 
Negative dates are not supported in **ConvertDateFromODataTime** function (ex: /Date(-1512691200000)/ ).

Below a regex that supports the minus char : 
`return new Date(parseInt(dateString.replace(/[^\d.|\-]/g, ""), 10));`

BR

**Pull request closed without merging**
